# Generated by Django 3.1.6 on 2021-02-04 17:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task_calendar', '0002_auto_20210204_1139'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='title',
            field=models.CharField(max_length=15),
        ),
    ]
